/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        serif:  ['Cormorant Garamond', 'Georgia', 'serif'],
        sans:   ['Poppins', 'Inter', 'sans-serif'],
        outfit: ['Outfit', 'sans-serif'],
      },
      colors: {
        kumkum:       '#B71C1C',
        'kumkum-light': '#C62828',
        haldi:        '#F4B400',
        saffron:      '#FF8F00',
        marigold:     '#FF6F00',
        sand:         '#FFF8EE',
        ivory:        '#FFFDF8',
        sandalwood:   '#F8F1E5',
        gold:         '#D4AF37',
        'gold-light': '#F4D483',
        brown:        '#5D4037',
        'deep-brown': '#3E2723',
        'deep-maroon':'#6D1B1B',
        'temple-brown':'#5D4037',
        lotus:        '#FDECEC',
        'light-gold': '#FDF3DC',
        saffron2:     '#FF8C00',
        sage:         '#8D9A7B',
        turmeric:     '#E8A800',
      },
      borderRadius: {
        '4xl': '2rem',
        '5xl': '2.5rem',
        '6xl': '3rem',
      },
      boxShadow: {
        'gold':    '0 8px 32px rgba(212,175,55,0.25)',
        'gold-lg': '0 16px 48px rgba(212,175,55,0.35)',
        'red':     '0 8px 32px rgba(183,28,28,0.20)',
        'divine':  '0 20px 60px rgba(93,64,55,0.15)',
        'card':    '0 4px 24px rgba(93,64,55,0.08)',
        'glow':    '0 0 40px rgba(212,175,55,0.35)',
        'inner-gold': 'inset 0 0 20px rgba(212,175,55,0.15)',
      },
      animation: {
        'float':          'float 6s ease-in-out infinite',
        'float-r':        'floatReverse 7s ease-in-out infinite',
        'breathe':        'breathe 4s ease-in-out infinite',
        'glow':           'glowPulse 2.5s ease-in-out infinite',
        'fade-up':        'fadeUp 0.6s ease-out forwards',
        'fade-in':        'fadeIn 0.5s ease-out forwards',
        'diya':           'divaGlow 2s ease-in-out infinite',
        'spin-slow':      'spinSlow 30s linear infinite',
        'spin-reverse':   'spinReverse 20s linear infinite',
        'petal':          'petalFall 10s linear infinite',
        'petal-l':        'petalFallLeft 12s linear infinite',
        'light-ray':      'lightRay 8s ease-in-out infinite',
        'bell':           'bellSwing 3s ease-in-out infinite',
        'slide-right':    'slideRight 0.5s ease-out forwards',
        'scale-in':       'scaleIn 0.4s ease-out forwards',
        'slide-down':     'slideDown 0.3s ease-out forwards',
        'text-glow':      'textGlow 3s ease-in-out infinite',
        'border-glow':    'borderGlow 2s ease-in-out infinite',
        'flame':          'flameFlicker 0.8s ease-in-out infinite',
        'shimmer-load':   'shimmerLoad 1.5s infinite',
        'gold-shimmer':   'goldenShimmer 3s ease infinite',
        'counter':        'counterUp 0.5s ease-out forwards',
        'ripple':         'ripple 1s ease-out forwards',
      },
      keyframes: {
        float:          { '0%,100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-14px) rotate(3deg)' } },
        floatReverse:   { '0%,100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(12px) rotate(-4deg)' } },
        breathe:        { '0%,100%': { transform: 'scale(1)', opacity: '0.8' }, '50%': { transform: 'scale(1.08)', opacity: '1' } },
        glowPulse:      { '0%,100%': { boxShadow: '0 0 20px rgba(212,175,55,0.3)' }, '50%': { boxShadow: '0 0 40px rgba(212,175,55,0.6), 0 0 80px rgba(255,143,0,0.2)' } },
        fadeUp:         { from: { opacity: '0', transform: 'translateY(30px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        fadeIn:         { from: { opacity: '0' }, to: { opacity: '1' } },
        divaGlow:       { '0%,100%': { filter: 'drop-shadow(0 0 4px #FF8F00)' }, '50%': { filter: 'drop-shadow(0 0 16px #F4B400) drop-shadow(0 0 32px #FF8F00)' } },
        petalFall:      { '0%': { transform: 'translateY(-60px) rotate(0deg) translateX(0)', opacity: '1' }, '100%': { transform: 'translateY(110vh) rotate(720deg) translateX(80px)', opacity: '0' } },
        petalFallLeft:  { '0%': { transform: 'translateY(-60px) rotate(0deg) translateX(0)', opacity: '1' }, '100%': { transform: 'translateY(110vh) rotate(-540deg) translateX(-60px)', opacity: '0' } },
        lightRay:       { '0%,100%': { opacity: '0.03' }, '50%': { opacity: '0.08' } },
        spinSlow:       { from: { transform: 'rotate(0deg)' }, to: { transform: 'rotate(360deg)' } },
        spinReverse:    { from: { transform: 'rotate(360deg)' }, to: { transform: 'rotate(0deg)' } },
        bellSwing:      { '0%,100%': { transform: 'rotate(0deg)', transformOrigin: 'top center' }, '20%': { transform: 'rotate(15deg)', transformOrigin: 'top center' }, '40%': { transform: 'rotate(-12deg)', transformOrigin: 'top center' }, '60%': { transform: 'rotate(8deg)', transformOrigin: 'top center' }, '80%': { transform: 'rotate(-5deg)', transformOrigin: 'top center' } },
        slideRight:     { from: { opacity: '0', transform: 'translateX(-30px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        scaleIn:        { from: { transform: 'scale(0.9)', opacity: '0' }, to: { transform: 'scale(1)', opacity: '1' } },
        slideDown:      { from: { transform: 'translateY(-20px)', opacity: '0' }, to: { transform: 'translateY(0)', opacity: '1' } },
        textGlow:       { '0%,100%': { textShadow: '0 0 10px rgba(244,180,0,0.3)' }, '50%': { textShadow: '0 0 20px rgba(244,180,0,0.7), 0 0 40px rgba(255,143,0,0.4)' } },
        borderGlow:     { '0%,100%': { boxShadow: '0 0 0 2px rgba(212,175,55,0.3)' }, '50%': { boxShadow: '0 0 0 4px rgba(212,175,55,0.6), 0 0 20px rgba(212,175,55,0.3)' } },
        flameFlicker:   { '0%,100%': { transform: 'scaleY(1) scaleX(1) rotate(-1deg)' }, '25%': { transform: 'scaleY(1.1) scaleX(0.95) rotate(1deg)' }, '50%': { transform: 'scaleY(0.95) scaleX(1.05) rotate(-0.5deg)' }, '75%': { transform: 'scaleY(1.05) scaleX(0.98) rotate(0.5deg)' } },
        shimmerLoad:    { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        goldenShimmer:  { '0%': { backgroundPosition: '-200% center' }, '100%': { backgroundPosition: '200% center' } },
        counterUp:      { from: { opacity: '0', transform: 'translateY(20px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        ripple:         { '0%': { transform: 'scale(0)', opacity: '0.6' }, '100%': { transform: 'scale(3)', opacity: '0' } },
      },
      backgroundImage: {
        'divine-gradient': 'linear-gradient(135deg, #B71C1C 0%, #FF8F00 50%, #F4B400 100%)',
        'temple-gradient': 'linear-gradient(135deg, #3E2723 0%, #5D4037 50%, #6D4C41 100%)',
        'gold-gradient':   'linear-gradient(135deg, #D4AF37 0%, #FF8F00 100%)',
        'lotus-gradient':  'linear-gradient(180deg, #FFF8EE 0%, #FDECEC 100%)',
        'maroon-gradient': 'linear-gradient(135deg, #6D1B1B 0%, #B71C1C 100%)',
        'hero-gradient':   'linear-gradient(135deg, #4A0E0E 0%, #B71C1C 40%, #FF6F00 80%, #F4B400 100%)',
        'night-gradient':  'linear-gradient(135deg, #0D0000 0%, #1A0808 50%, #2D1010 100%)',
      },
      transitionTimingFunction: {
        'spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        'smooth': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      spacing: {
        '18': '4.5rem',
        '22': '5.5rem',
        '26': '6.5rem',
        '30': '7.5rem',
        '34': '8.5rem',
      },
      fontSize: {
        '2xs': ['0.625rem', { lineHeight: '0.875rem' }],
        '10xl': ['10rem', { lineHeight: '1' }],
      },
      zIndex: {
        '60': '60',
        '70': '70',
        '80': '80',
        '90': '90',
        '100': '100',
      },
      backdropBlur: {
        'xs': '2px',
      },
      screens: {
        'xs': '480px',
      },
    },
  },
  plugins: [],
}
